Feature/tcan bridge
leggedrobotics/tcan pull request #6
Opened 2022-07-13 06:32 UTC by simonkerscher

This creates nodes that convert CAN-messages to ROS2-messages and vice versa. Could be useful to connect CAN-controlled visualizers and input devices at remote locations. 

See this terminal output for the node in action. The clocks between computers are not synchronized. The delay introduced by the bridge and the networking (local Ethernet switch in this case) seems to be <5ms.

![image](https://user-images.githubusercontent.com/9860308/178665774-97eedafe-220a-4cea-9ccc-9afff1197498.png)

2022-07-13 10:18 UTC, djud requested changes
There is some duplication in the three executables (bidirectional, can to ros and ros to can). Imo this could be reduced to just the bidirectional bridge by adding a check to the publisher if there is a subscriber to the topic it publishes. The other direction does not have to be checked, becuase there will be no callback triggered if there are no messages published on the topics.

2022-07-13 10:18 UTC, djud commented on tcan_bridge/.clang-format
> +/home/kersimon/workspaces/.clang-format
remove this file?

2022-07-13 10:18 UTC, djud commented on tcan_bridge/package.xml
> +  <license>TODO: License declaration</license>
MIT as everything else?

2022-07-13 10:18 UTC, djud commented on tcan_bridge/package.xml
> +  <description>TODO: Package description</description>
fill in

2022-07-13 10:18 UTC, djud commented on tcan_bridge_msgs/package.xml
> +  <description>TODO: Package description</description>
fill in description and license

2022-07-13 10:18 UTC, djud commented on tcan_bridge/src/bidirectional_bridge.cpp
> +  BidirectionalBridge(const std::string& nodeName, const std::string& canInterfaceName, const std::string& publishedName,
change `publishedName` to `publishedTopicName`

2022-07-13 10:18 UTC, djud commented on tcan_bridge/src/bidirectional_bridge.cpp
> +                      const std::string& subscribedName)
change `subscribedName` to `subscribedTopicName`

2022-07-13 10:18 UTC, djud commented on tcan_bridge/src/bidirectional_bridge.cpp
> +  std::vector<rclcpp::Subscription<tcan_bridge_msgs::msg::CanFrame>::SharedPtr> subscribers_;
why is there a vector of subscribers if we only have one?

2022-07-13 10:18 UTC, djud commented on tcan_bridge/src/bidirectional_bridge.cpp
> +  const std::string nodeName = canInterfaceName + "_to_" + publishedName + "_and_from_" + subscribedName + "_bridge_";
interface, published and subscribed topic name should be ros2 parameters. They can then still be set through the commandline but we can also do proper config files

2022-07-14 15:45 UTC, simonkerscher commented on tcan_bridge/src/bidirectional_bridge.cpp
> +  std::vector<rclcpp::Subscription<tcan_bridge_msgs::msg::CanFrame>::SharedPtr> subscribers_;
My plan was to have config files that allowed multiple forwardings with one node, however never finished this

2022-07-14 16:01 UTC, simonkerscher commented on tcan_bridge/src/bidirectional_bridge.cpp
> +  const std::string nodeName = canInterfaceName + "_to_" + publishedName + "_and_from_" + subscribedName + "_bridge_";
Will do this tomorrow

2022-07-15 09:16 UTC, djud approved these changes

2022-07-15 12:35 UTC, merged